version: "1.0"

services:
  postgres:
    image: postgres:15
    container_name: postgres-alpha
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/ubuntu/db/postgres/data:/var/lib/postgresql/data
