version: '1.0'

services:
  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan-app
    ports: 8081:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://1.15.230.172:27017/wekan
      - ROOT_URL=http://1.15.230.172
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw
