version: '1.0'

services: 
  kanboard:
    image: kanboard/kanboard
    container_name: kanboard-alpha
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/kanboard/kanboard_data:/var/www/app/data
      - /home/ubuntu/kanboard/kanboard_plugins:/var/www/app/plugins
      - /home/ubuntu/kanboard/kanboard_ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
