version: '1.0'

services: 
  kanboard:
    image: kanboard/kanboard
    container_name: kanboard-alpha
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data: /home/ubuntu/kanboard/kanboard_data
  kanboard_plugins: /home/ubuntu/kanboard/kanboard_plugins
  kanboard_ssl: /home/ubuntu/kanboard/kanboard_ssl
